{{-- NGO.Tools Laravel Starter SDK - Boost Guidelines for AI Code Assistants --}}
{{-- Package: ngo-tools/sdk-laravel-starter --}}

## NGO.Tools App SDK

This application is an **extension** (third-party app) for the NGO.Tools platform, built with `ngo-tools/sdk-laravel-starter`.

### Mental Model — Read This First

This app is a **plugin** that extends NGO.Tools. It does NOT own domain data like contacts, donations, or projects — those live in NGO.Tools. This app can:

1. **Display UI** inside NGO.Tools via iframe (UI slots)
2. **React to events** from NGO.Tools via webhooks (e.g. `contact.created`, `donation.created`)
3. **Read/write data** in NGO.Tools via its REST API using a Bearer token

When a user says "when a contact is created", they mean: **when NGO.Tools sends a `contact.created` webhook to this app** — NOT that this app should create contacts itself. The same applies to donations, members, etc.

**Data flow:** NGO.Tools → webhook → this app reacts. Or: this app → API call → reads/writes data in NGO.Tools.

### Architecture

- The app is rendered inside an **iframe** in the NGO.Tools admin panel
- Communication with the parent frame uses a **postMessage bridge** (global `NGOTools` JS object)
- **Webhooks** from NGO.Tools arrive as HMAC-SHA256 signed POST requests at `routes/ngotools-webhooks.php`
- **API access** uses a Bearer token provided through the bridge init state (`state.accessToken`)

### Artisan Commands

- `php artisan ngotools:install` — Interactive setup wizard (UI slots, webhooks, scopes)
- `php artisan ngotools:dev` — Starts dev server + cloudflared tunnel, registers tunnel with NGO.Tools

### File Structure (app-side, generated by install wizard)

- `routes/ngotools-ui.php` — UI routes for iframe pages
- `routes/ngotools-webhooks.php` — Webhook handler routes (incoming events from NGO.Tools)
- `resources/views/ngotools/pages/` — Blade views for UI slots
- `config/ngotools.php` — Configuration (API URL, dev token, webhook secret, port)

### Layout & Bridge

- Views must extend `ngotools::layouts.app` (from the package — never publish or override this layout)
- The bridge JS is inlined in the layout to avoid PNA/CORS issues with dev tunnels
- Tailwind CSS is loaded via CDN in the layout — no build step needed for simple apps

#### JavaScript Bridge API

```javascript
NGOTools.onInit(callback)       // Register callback for init state (called when iframe loads)
NGOTools.getState()             // Return deep copy of current state
NGOTools.sendNavigate(route)    // Trigger navigation in parent frame
NGOTools.applyTheme(theme)      // Apply 'light' or 'dark' mode
NGOTools.enableDevMode(options) // Simulate init outside iframe (dev only)
```

The `ngotools:init` CustomEvent is dispatched on `document` after initialization:

```javascript
document.addEventListener('ngotools:init', function(e) {
    var state = e.detail;
    // state.user.name, state.tenantId, state.locale, etc.
});
```

#### Bridge State Structure

| Field | Type | Description |
|-------|------|-------------|
| `accessToken` | string | Bearer token for NGO.Tools API |
| `tenantId` | number | Current tenant/organization ID |
| `locale` | string | User locale (`de`, `en`, ...) |
| `theme` | `light` \| `dark` | Current UI theme |
| `primaryColor` | string | Hex color from NGO.Tools theme |
| `apiBaseUrl` | string | Base URL for API requests |
| `user` | object | `{ id, name }` of the logged-in user |
| `context` | object | `{ entityType, entityId }` — set on contact tabs etc. |

### UI Slots

| Slot | Route | Use case |
|------|-------|----------|
| `navigation_entry` | `ui` | Full page under a navigation link |
| `dashboard_card` | `ui/widget` | Widget card on the dashboard |
| `contact_tab` | `ui/contact` | Tab on the contact detail page (receives `context.entityId`) |

### Webhooks (Incoming Events from NGO.Tools)

NGO.Tools sends webhooks to this app when things happen in the platform. The app **receives and reacts** to these events — it does not trigger them.

Available events: `contact.created`, `contact.updated`, `contact.deleted`, `donation.created`

- Webhook handler: `routes/ngotools-webhooks.php`
- Signature header: `X-NGOTools-Signature` (HMAC-SHA256)
- Timestamp header: `X-NGOTools-Timestamp` (unix seconds)
- Event header: `X-NGOTools-Event` (e.g. `contact.created`)
- Signature formula: `hash_hmac('sha256', timestamp . '.' . rawBody, secret)`
- Replay protection: ±300 seconds tolerance
- Use `VerifyWebhookSignature` middleware on webhook routes

### NGO.Tools REST API (Outgoing Requests)

To read or write data in NGO.Tools, use the API with the token from the bridge state:

```php
Http::withToken($accessToken)
    ->baseUrl($apiBaseUrl)
    ->get('/contacts');
```

This app does NOT have its own contacts/donations/members tables. It accesses NGO.Tools data exclusively through the API.

### Important Rules

- This app is an **extension** — it does not own contacts, donations, or other NGO.Tools domain data
- NEVER publish or override `ngotools::layouts.app` — it stays in the package and auto-updates
- Views live in `resources/views/ngotools/pages/` (app views), NOT in `resources/views/vendor/`
- `AllowIframeEmbedding` middleware is automatically applied to all UI routes by the service provider
- When making API calls to NGO.Tools, use `state.apiBaseUrl` with `Authorization: Bearer {state.accessToken}`
- The `.env` keys are: `NGOTOOLS_API_URL`, `NGOTOOLS_DEV_TOKEN`, `NGOTOOLS_WEBHOOK_SECRET`, `NGOTOOLS_PORT`
